config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :trips do
    get "posts", to: "posts#index_trip", as: :posts
    get "posts/new", to: "posts#new_trip", as: :new_post
    get "media_items", to: "media_items#index_trip", as: :media_items
    get "media_items/new", to: "media_items#new_trip", as: :new_media_item
    put "set_cover_photo/:media_item_id", to: "trips#set_cover_photo", as: :set_cover_photo

    post :like, to: "trips/likes#create"
    delete :like, to: "trips/likes#destroy"

    resources :comments, module: :trips
    resources :trip_users

    resources :segments do
      put "increase_sequence", to: "segments#increase_sequence", as: :increase_sequence
      put "decrease_sequence", to: "segments#decrease_sequence", as: :decrease_sequence
    end

    resources :waypoints do
      get "media_items", to: "media_items#index_waypoint", as: :media_items
      get "media_items/new", to: "media_items#new_waypoint", as: :new_media_item
      get "posts", to: "posts#index_waypoint", as: :posts
      get "posts/new", to: "posts#new_waypoint", as: :new_post
      put "increase_sequence", to: "waypoints#increase_sequence", as: :increase_sequence
      put "decrease_sequence", to: "waypoints#decrease_sequence", as: :decrease_sequence
    end
  end

  get "waypoints/search/:keyword", to: "waypoints#search", as: :waypoints_search
  get "waypoints/distance/:id_from/:id_to", to: "waypoints#distance", as: :waypoints_distance

  resources :activities, only: %i[index show] do
    resources :comments, module: :activities
    post :like, to: "activities/likes#create"
    delete :like, to: "activities/likes#destroy"
  end

  resources :posts, except: :index do
    resources :comments, module: :posts
    post :like, to: "posts/likes#create"
    delete :like, to: "posts/likes#destroy"
  end

  resources :media_items, except: :index do
    resources :comments, module: :media_items
    post :like, to: "media_items/likes#create"
    delete :like, to: "media_items/likes#destroy"
  end

  resources :users, only: :show do
    post "follow", to: "users#follow", as: :follow
    delete "unfollow", to: "users#unfollow", as: :unfollow
  end

  resources :comments, only: %i[update edit destroy] do
    post :like, to: "comments/likes#create"
    delete :like, to: "comments/likes#destroy"
  end

  get "home/index", as: :home
  get "summary/overall", as: :summary_overall
  get "summary/current_year", as: :summary_current_year
  get "summary/last_year", as: :summary_last_year

  get "media_items_public", to: "media_items#index_public", as: :media_items_public
  get "posts_public", to: "posts#index_public", as: :posts_public
  get "trips_public", to: "trips#index_public", as: :trips_public

  root "home#index"
end

app/views/shared/_back_button.html.erb
<%= link_to target, class: 'btn btn-large btn-outline-dark mb-4' do %>
  <i class="bi bi-arrow-left"></i>
<% end %>

app/views/shared/_comments_button.html.erb
<div class="comments-button">
  <%= link_to comments_path(commentable) do %>
    <i class="bi bi-chat-right"></i>
  <% end %>
  <%= commentable.comments_count %>
</div>

app/views/shared/_confirm_button.html.erb
<button type="submit" form=<%= local_assigns[:form] %> class="btn btn-dark mb-4">
  <i class="bi bi-check mx-1"></i>Confirm
</button>

app/views/shared/_delete_button.html.erb
<%= link_to target, method: :delete, data: { confirm: local_assigns[:message] || 'Are you sure?' }, class: 'btn btn-outline-dark mb-4' do %>
  <i class="bi bi-trash mx-1"></i>Delete
<% end %>

app/views/shared/_edit_button.html.erb
<%= link_to target, class: 'btn btn-outline-dark mb-4' do %>
  <i class="bi bi-pencil mx-1"></i>Edit
<% end %>

app/views/shared/_like_button.html.erb
<%= turbo_frame_tag element_id("like-button", likeable), class: "like-button" do %>
  <% liked = local_assigns[:user].present? ? likeable.liked_by?(user) : false %>
  <%= link_to_if local_assigns[:clickable].presence,
    icon_thumbs_up(likeable, liked).html_safe,
    like_path(likeable),
    method: liked ? :delete : :post,
    id: element_id("like-link", likeable)
  %>
  <span id=<%= element_id("like-counter", likeable) %>><%= likeable.likes_count %></span>
<% end %>

app/views/shared/_map.html.erb
<h2 class="display-6 mt-5 mb-4">Map</h2>
<div id="mapid" class="map-container"></div>
<script>
  function onMapElementClick(e) {
    location.href = e.originalEvent.target.innerHTML
  }

	var mymap = L.map('mapid', {
    center: [0, 0],
    zoom: 1,
    gestureHandling: true
  })

  // tiles
	L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoiY2hyaWxhIiwiYSI6ImNrbzF4ZWJhcjBwZmQycG1zbWRodWM1cm8ifQ.M0TKFhXK_SzhWqokJpDE4Q', {
		maxZoom: 18,
		attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, ' +
			'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
		id: 'mapbox/streets-v11',
		tileSize: 512,
		zoomOffset: -1
	}).addTo(mymap)

  <% if local_assigns[:waypoints].present? %>
    // draw waypoints
    var markers = []
    var m
    <% waypoints.each do |w| %>
      m = L.marker([<%= w.lat_long_str %>], {
        title: '<%= w.seq_name_str %>'
      }).addTo(mymap)
      markers.push(m)
      // hack: store link to waypoint inside markers image
      m._icon.innerHTML = "<%= url_for([w.trip, w]) %>"
      m.on('click', onMapElementClick)
    <% end %>

    // zoom the map to show all markers
    var group = new L.featureGroup(markers)
    mymap.fitBounds(group.getBounds())

    // if there's only one marker, set zoom level to actually see something
    if (markers.length == 1) {
      mymap.setZoom(10)
    }
  <% end %>

  <% if local_assigns[:segments].present? %>
    // draw segments
    var line, pl
    <% segments.each do |s| %>
      line = [[<%= s.waypoint_from.lat_long_str %>], [<%= s.waypoint_to.lat_long_str %>]]
      pl = L.polyline(line, {
        color: '<%= segment_status_color(s) %>'
      }).addTo(mymap)
      // hack: store link to waypoint inside polyline's path
      pl._path.innerHTML = "<%= url_for([s.trip, s]) %>"
      pl.on('click', onMapElementClick)
    <% end %>
  <% end %>

</script>

app/views/shared/_navbar.html.erb
<nav id="navbar" class="navbar navbar-expand-lg navbar-light p-3 mb-3 sticky-top shadow">
  <div class="container">
    <%= link_to 'trvlr', root_path, class: 'navbar-brand trvlr-logo text-white shadow' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarToggler">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if signed_in? %>
          <li class="nav-item">
            <%= link_to activities_path, class: 'nav-link' do %>
              <i class="bi bi-rss mx-2"></i>Activity stream
            <% end%>
          </li>
          <li class="nav-item">
            <%= link_to trips_path, class: 'nav-link' do %>
              <i class="bi bi-compass mx-2"></i>My trips
            <% end%>
          </li>
          <li class="nav-item">
            <%= link_to summary_current_year_path, class: 'nav-link' do %>
              <i class="bi bi-bar-chart-line mx-2"></i>Summary
            <% end%>
          </li>
          <li class="nav-item">
            <%= link_to user_path(current_user.id), class: 'nav-link' do %>
              <i class="bi bi-person-circle mx-2"></i><%= current_user.username %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
              <i class="bi bi-box-arrow-left mx-2"></i>Sign Out
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-outline-light shadow' %>
          </li>
          <li class="nav-item mx-2 my-1">
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-outline-light shadow'%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navbar_trips.html.erb
<div class="btn-group mb-4">
  <%= render 'shared/trip_overview_button', trip: @trip %>
  <%= render 'shared/trip_users_button', trip: @trip %>
  <%= render 'shared/trip_waypoints_button', trip: @trip %>
  <%= render 'shared/trip_segments_button', trip: @trip %>
  <%= render 'shared/trip_posts_button', trip: @trip %>
  <%= render 'shared/trip_media_items_button', trip: @trip %>
</div>

app/views/shared/_trip_media_items_button.html.erb
<%= link_to trip_media_items_path(trip), class: class_names('btn btn-outline-dark', 'active': local_assigns[:active] == 'media_items') do %>
  <i class="bi bi-images mx-1"></i><span class="d-none d-md-inline">Media</span>
<% end %>

app/views/shared/_trip_overview_button.html.erb
<%= link_to trip, class: class_names('btn btn-outline-dark', 'active': local_assigns[:active] == 'overview') do %>
  <i class="bi bi-compass mx-1"></i><span class="d-none d-md-inline">Overview</span>
<% end %>

app/views/shared/_trip_segments_button.html.erb
<%= link_to trip_segments_path(trip), class: class_names('btn btn-outline-dark', 'active': local_assigns[:active] == 'segments') do %>
  <i class="bi bi-bezier2 mx-1"></i><span class="d-none d-md-inline">Segments</span>
<% end %>

app/views/shared/_trip_waypoints_button.html.erb
<%= link_to trip_waypoints_path(trip), class: class_names('btn btn-outline-dark', 'active': local_assigns[:active] == 'waypoints') do %>
  <i class="bi bi-geo-alt mx-1"></i><span class="d-none d-md-inline">Waypoints</span>
<% end %>

app/views/shared/_trips_navbar.html.erb
<div class="btn-group mb-4 w-100">
  <%= render 'shared/trip_overview_button', trip: @trip, active: local_assigns[:active] %>
  <%= render 'shared/trip_participants_button', trip: @trip, active: local_assigns[:active] %>
  <%= render 'shared/trip_waypoints_button', trip: @trip, active: local_assigns[:active] %>
  <%= render 'shared/trip_segments_button', trip: @trip, active: local_assigns[:active] %>
  <%= render 'shared/trip_posts_button', trip: @trip, active: local_assigns[:active] %>
  <%= render 'shared/trip_media_items_button', trip: @trip, active: local_assigns[:active] %>
</div>