config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :trips do
    get "posts", to: "posts#index_trip", as: :posts
    get "posts/new", to: "posts#new_trip", as: :new_post
    get "media_items", to: "media_items#index_trip", as: :media_items
    get "media_items/new", to: "media_items#new_trip", as: :new_media_item
    put "set_cover_photo/:media_item_id", to: "trips#set_cover_photo", as: :set_cover_photo

    post :like, to: "trips/likes#create"
    delete :like, to: "trips/likes#destroy"

    resources :comments, module: :trips
    resources :trip_users

    resources :segments do
      put "increase_sequence", to: "segments#increase_sequence", as: :increase_sequence
      put "decrease_sequence", to: "segments#decrease_sequence", as: :decrease_sequence
    end

    resources :waypoints do
      get "media_items", to: "media_items#index_waypoint", as: :media_items
      get "media_items/new", to: "media_items#new_waypoint", as: :new_media_item
      get "posts", to: "posts#index_waypoint", as: :posts
      get "posts/new", to: "posts#new_waypoint", as: :new_post
      put "increase_sequence", to: "waypoints#increase_sequence", as: :increase_sequence
      put "decrease_sequence", to: "waypoints#decrease_sequence", as: :decrease_sequence
    end
  end

  get "waypoints/search/:keyword", to: "waypoints#search", as: :waypoints_search
  get "waypoints/distance/:id_from/:id_to", to: "waypoints#distance", as: :waypoints_distance

  resources :activities, only: %i[index show] do
    resources :comments, module: :activities
    post :like, to: "activities/likes#create"
    delete :like, to: "activities/likes#destroy"
  end

  resources :posts, except: :index do
    resources :comments, module: :posts
    post :like, to: "posts/likes#create"
    delete :like, to: "posts/likes#destroy"
  end

  resources :media_items, except: :index do
    resources :comments, module: :media_items
    post :like, to: "media_items/likes#create"
    delete :like, to: "media_items/likes#destroy"
  end

  resources :users, only: :show do
    post "follow", to: "users#follow", as: :follow
    delete "unfollow", to: "users#unfollow", as: :unfollow
  end

  resources :comments, only: %i[update edit destroy] do
    post :like, to: "comments/likes#create"
    delete :like, to: "comments/likes#destroy"
  end

  get "home/index", as: :home
  get "summary/overall", as: :summary_overall
  get "summary/current_year", as: :summary_current_year
  get "summary/last_year", as: :summary_last_year

  get "media_items_public", to: "media_items#index_public", as: :media_items_public
  get "posts_public", to: "posts#index_public", as: :posts_public
  get "trips_public", to: "trips#index_public", as: :trips_public

  root "home#index"
end

app/models/segment.rb
# frozen_string_literal: true

class Segment < ApplicationRecord
  include Sequencable

  belongs_to :trip
  belongs_to :waypoint_from, class_name: "Waypoint"
  belongs_to :waypoint_to, class_name: "Waypoint"
  belongs_to :means_of_travel

  enum status: %i[segment_open segment_active segment_finished]

  scope :finished_between, lambda { |date_from, date_to|
    segment_finished.where("segments.time_to between ? and ?", date_from, date_to)
  }

  validates :waypoint_from, presence: true
  validates :waypoint_to, presence: true
  validates :time_from, presence: true
  validates :time_to, presence: true
  validates :status, presence: true, inclusion: { in: Segment.statuses, message: "is invalid" }

  def status_string
    status.split("_").last.humanize
  end

  def activity_string
    "a segment"
  end

  private
    def data_collection
      trip.segments
    end
end

app/controllers/segments_controller.rb
# frozen_string_literal: true

class SegmentsController < ApplicationController
  include Pagy::Backend

  before_action :set_trip
  before_action :set_segment, only: %i[show edit update destroy increase_sequence decrease_sequence]
  authorize_resource

  def index
    @pagy, @segments = pagy(@trip.segments.order(:sequence, :id))
  end

  def new
    @segment = @trip.segments.build

    # set default values based on previous segment
    last_sg = @trip.segments.find_by(sequence: @trip.segments.maximum(:sequence))
    return unless last_sg

    @segment.waypoint_from = last_sg.waypoint_to
    @segment.waypoint_to = last_sg.waypoint_to
    @segment.time_from = last_sg.time_to
    @segment.time_to = last_sg.time_to
    @segment.means_of_travel = last_sg.means_of_travel
  end

  def edit
  end

  def show
  end

  def create
    @segment = @trip.segments.build(segment_params)

    respond_to do |format|
      if @segment.save
        format.html { redirect_to trip_segments_path(@trip), notice: "Segment was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @segment.update(segment_params)
        format.html { redirect_to trip_segments_path(@trip), notice: "Segment was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @segment.destroy
        format.html { redirect_to trip_segments_path(@trip), notice: "Segment was successfully deleted." }
      else
        format.html { redirect_to trip_segments_path(@trip), alert: "Segment could not be deleted." }
      end
    end
  end

  def decrease_sequence
    @segment.decrease_sequence

    respond_to do |format|
      format.html { redirect_to trip_segments_path(@trip) }
    end
  end

  def increase_sequence
    @segment.increase_sequence

    respond_to do |format|
      format.html { redirect_to trip_segments_path(@trip) }
    end
  end

  private
    def segment_params
      params.require(:segment).permit(%i[waypoint_from_id waypoint_to_id time_from time_to distance status means_of_travel_id])
    end

    def set_trip
      @trip = Trip.find(params[:trip_id])
    end

    def set_segment
      @segment = @trip.segments.find(params[:id] || params[:segment_id])
    end
end

app/helpers/segments_helper.rb
# frozen_string_literal: true

module SegmentsHelper
  def waypoints_for_select(trip)
    trip.waypoints.order(:sequence).collect { |w| [w.seq_name_str, w.id] }
  end

  def segment_statuses_list
    Segment.statuses.keys.collect { |k| [k.split("_").last.humanize, k] }
  end

  def means_of_travel_list
    MeansOfTravel.order(:name).collect { |m| [m.name, m.id] }
  end

  def segment_status_color(segment)
    colors = {
      segment_open: "black",
      segment_active: "#ffc107", # yellow
      segment_finished: "#198754" # green
    }
    colors[segment.status.to_sym]
  end

  def segment_status_bg_class(segment)
    bg_classes = {
      segment_open: "bg-dark",
      segment_active: "bg-warning font-dark",
      segment_finished: "bg-success"
    }
    bg_classes[segment.status.to_sym]
  end
end

app/views/segments/_form.html.erb
<%= form_with(model: [@trip, segment], local: true, id: 'segment-form') do |f| %>
  <% if segment.errors.any? %>
    <div class="form-error-list">
      <h2><%= pluralize(segment.errors.count, "error") %> prohibited this segment from being saved:</h2>
      <ul>
      <% segment.errors.full_messages.each do |e| %>
        <li><%= e %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div data-controller="segment">
    <div class="form-group my-2">
      <%= f.label :waypoint_from %>
      <%= f.select :waypoint_from_id, waypoints_for_select(@trip), {}, class: 'form-select',
        data: { "segment-target": "from", "action": "change->segment#calculateDistance" } %>
    </div>

    <div class="form-group my-2">
      <%= f.label :waypoint_to %>
      <%= f.select :waypoint_to_id, waypoints_for_select(@trip), {}, class: 'form-select',
        data: { "segment-target": "to", "action": "change->segment#calculateDistance" } %>
    </div>

    <div class="form-group my-2">
      <%= f.label :time_from, 'From' %>
      <%= f.date_field :time_from, class: 'form-control' %>
    </div>

    <div class="form-group my-2">
      <%= f.label :time_to, 'Until' %>
      <%= f.date_field :time_to, class: 'form-control' %>
    </div>

    <div class="form-group my-2">
      <%= f.label :distance %>
      <%= f.text_field :distance, class: 'form-control', data: { "segment-target": "distance" } %>
    </div>

    <div class="form-group my-2">
      <%= f.label :status %>
      <%= f.select :status, segment_statuses_list, {}, class: 'form-select' %>
    </div>

    <div class="form-group my-2">
      <%= f.label :means_of_travel %>
      <%= f.select :means_of_travel_id, means_of_travel_list, {}, class: 'form-select' %>
    </div>
  </div>
<% end %>

app/views/segments/_segment.html.erb
<%= tag.tr class: class_names("segment-table-row-#{segment.status_string.downcase}"), id: dom_id(segment) do %>
  <th scope="row"><%= segment.sequence %></th>
  <td><%= link_to segment.waypoint_from.name, [@trip, segment] %></td>
  <td><%= link_to segment.waypoint_to.name, [@trip, segment] %></td>
  <td class="d-none d-lg-table-cell"><%= segment.time_from.to_s(:day_and_year) %></td>
  <td class="d-none d-md-table-cell d-lg-none"><%= segment.time_from.to_s(:day) %></td>
  <td class="d-none d-lg-table-cell"><%= segment.time_to.to_s(:day_and_year) %></td>
  <td class="d-none d-md-table-cell d-lg-none"><%= segment.time_to.to_s(:day) %></td>
  <td class="d-none d-sm-table-cell"><%= segment.distance.round(1) %></td>
  <td class="d-none d-md-table-cell"><%= render 'segment_status_button', segment: segment %></td>
    <td class="d-none d-md-table-cell">
      <div class="table-row-action-items">
  <% if can? :manage, segment %>
        <%= link_to edit_trip_segment_path(@trip, segment) do %>
          <i class="bi bi-pencil"></i>
        <% end %>
        <%= link_to trip_segment_path(@trip, segment), method: :delete, data: { confirm: 'Are you sure?' } do %>
          <i class="bi bi-trash"></i>
        <% end %>
  <% end %>
      </div>
    </td>
  <% if can? :manage, segment %>
    <td>
      <% unless segment.first? %>
        <%= link_to trip_segment_decrease_sequence_path(@trip, segment), method: :put do %>
          <i class="bi bi-arrow-up"></i>
        <% end %>
      <% end %>
    </td>
    <td>
      <% unless segment.last? %>
        <%= link_to trip_segment_increase_sequence_path(@trip, segment), method: :put do %>
          <i class="bi bi-arrow-down"></i>
        <% end %>
      <% end %>
    </td>
  <% end %>
<% end %>

app/views/segments/_segment_status_button.html.erb
<%= tag.span segment.status_string, class: class_names('badge', segment_status_bg_class(segment)) %>

app/views/segments/edit.html.erb
<%= render 'shared/trips_header', trip: @trip, title: 'Edit segment', navbar: false %>

<%= render 'shared/back_button', target: :back %>
<%= render 'shared/confirm_button', form: 'segment-form' %>

<%= render 'form', segment: @segment %>

app/views/segments/index.html.erb
<%= render 'shared/trips_header', trip: @trip, title: 'Segments', active: 'segments' %>

<% if can? :manage, @trip %>
  <%= render 'shared/add_button', target: new_trip_segment_path(@trip), resource: 'segment' %>
<% end %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">From</th>
      <th scope="col">To</th>
      <th scope="col" class="d-none d-md-table-cell">Start</th>
      <th scope="col" class="d-none d-md-table-cell">End</th>
      <th scope="col" class="d-none d-sm-table-cell">Distance</th>
      <th scope="col" class="d-none d-md-table-cell">Status</th>
      <% if can? :read, @trip %>
        <!-- links to show, edit, delete -->
        <th scope="col" class="d-none d-md-table-cell"></th>
      <% end %>
      <% if can? :manage, @trip %>
        <!-- move up (decrease sequence) -->
        <th scope="col"></th>
        <!-- move down (increase sequence) -->
        <th scope="col"></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <%= render @segments %>
  </tbody>
</table>

<% if @pagy.pages > 1%>
  <div class="my-5 text-center">
    <%== pagy_bootstrap_nav @pagy %>
  </div>
<% end %>

app/views/segments/new.html.erb
<%= render 'shared/trips_header', trip: @trip, title: 'Add segment', navbar: false %>

<%= render 'shared/back_button', target: trip_segments_path(@trip) %>
<%= render 'shared/confirm_button', form: 'segment-form' %>

<%= render 'form', segment: @segment %>

app/views/segments/show.html.erb
<%= render 'shared/trips_header', trip: @trip, title: 'Segment details', navbar: false %>

<%= render 'shared/back_button', target: trip_segments_path(@trip) + "\##{dom_id(@segment)}" %>
<% if can? :manage, @segment %>
    <%= render 'shared/edit_button', target: edit_trip_segment_path(@trip, @segment) %>
    <%= render 'shared/delete_button', target: trip_segment_path(@trip, @segment) %>
<% end %>

<p class="fs-3 fw-light"><strong>From: </strong><%= link_to @segment.waypoint_from.name, [@trip, @segment.waypoint_from] %></p>
<p class="fs-3 fw-light"><strong>To: </strong><%= link_to @segment.waypoint_to.name, [@trip, @segment.waypoint_to] %></p>
<p class="fs-3 fw-light"><strong>Start: </strong><%= @segment.time_from.to_s(:day_and_year) %></p>
<p class="fs-3 fw-light"><strong>End: </strong><%= @segment.time_to.to_s(:day_and_year) %></p>
<p class="fs-3 fw-light"><strong>Distance: </strong><%= "#{@segment.distance.round(2)} km" %></p>
<p class="fs-3 fw-light"><strong>Status: </strong><%= tag.span @segment.status_string, class: class_names('badge', segment_status_bg_class(@segment)) %></p>
<p class="fs-3 fw-light"><strong>Means of travel: </strong><%= @segment.means_of_travel %></p>

<%= render 'shared/map', waypoints: [@segment.waypoint_from, @segment.waypoint_to], segments: [@segment] %>