config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :trips do
    get "posts", to: "posts#index_trip", as: :posts
    get "posts/new", to: "posts#new_trip", as: :new_post
    get "media_items", to: "media_items#index_trip", as: :media_items
    get "media_items/new", to: "media_items#new_trip", as: :new_media_item
    put "set_cover_photo/:media_item_id", to: "trips#set_cover_photo", as: :set_cover_photo

    post :like, to: "trips/likes#create"
    delete :like, to: "trips/likes#destroy"

    resources :comments, module: :trips
    resources :trip_users

    resources :segments do
      put "increase_sequence", to: "segments#increase_sequence", as: :increase_sequence
      put "decrease_sequence", to: "segments#decrease_sequence", as: :decrease_sequence
    end

    resources :waypoints do
      get "media_items", to: "media_items#index_waypoint", as: :media_items
      get "media_items/new", to: "media_items#new_waypoint", as: :new_media_item
      get "posts", to: "posts#index_waypoint", as: :posts
      get "posts/new", to: "posts#new_waypoint", as: :new_post
      put "increase_sequence", to: "waypoints#increase_sequence", as: :increase_sequence
      put "decrease_sequence", to: "waypoints#decrease_sequence", as: :decrease_sequence
    end
  end

  get "waypoints/search/:keyword", to: "waypoints#search", as: :waypoints_search
  get "waypoints/distance/:id_from/:id_to", to: "waypoints#distance", as: :waypoints_distance

  resources :activities, only: %i[index show] do
    resources :comments, module: :activities
    post :like, to: "activities/likes#create"
    delete :like, to: "activities/likes#destroy"
  end

  resources :posts, except: :index do
    resources :comments, module: :posts
    post :like, to: "posts/likes#create"
    delete :like, to: "posts/likes#destroy"
  end

  resources :media_items, except: :index do
    resources :comments, module: :media_items
    post :like, to: "media_items/likes#create"
    delete :like, to: "media_items/likes#destroy"
  end

  resources :users, only: :show do
    post "follow", to: "users#follow", as: :follow
    delete "unfollow", to: "users#unfollow", as: :unfollow
  end

  resources :comments, only: %i[update edit destroy] do
    post :like, to: "comments/likes#create"
    delete :like, to: "comments/likes#destroy"
  end

  get "home/index", as: :home
  get "summary/overall", as: :summary_overall
  get "summary/current_year", as: :summary_current_year
  get "summary/last_year", as: :summary_last_year

  get "media_items_public", to: "media_items#index_public", as: :media_items_public
  get "posts_public", to: "posts#index_public", as: :posts_public
  get "trips_public", to: "trips#index_public", as: :trips_public

  root "home#index"
end

app/models/media_item.rb
# frozen_string_literal: true

class MediaItem < ApplicationRecord
  include ActivitySubject
  include Likeable

  belongs_to :waypoint
  belongs_to :user
  has_one :trip, through: :waypoint
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :activities, as: :subject, dependent: :destroy
  has_one :trip_cover_photo, class_name: "Trip", foreign_key: :cover_photo_id, dependent: :nullify

  has_one_attached :photo

  attr_readonly :likes_count
  attr_readonly :comments_count

  scope :created_between, ->(date_from, date_to) { where("created_at between ? and ?", date_from, date_to) }
  scope :most_popular_public, lambda {
    joins(:waypoint)
      .joins(:trip)
      .where("trips.visibility = ?", Trip.visibilities["visibility_public"])
      .order(likes_count: :desc, comments_count: :desc)
  }

  validates :title, presence: true
  validates :photo, presence: true

  def activity_string
    "a media item"
  end
end

app/controllers/media_items/comments_controller.rb
# frozen_string_literal: true

class MediaItems::CommentsController < ApplicationController
  include CommentableController

  before_action :set_commentable

  private
    def set_commentable
      @commentable = MediaItem.find(params[:media_item_id])
    end
end

app/controllers/media_items/likes_controller.rb
# frozen_string_literal: true

class MediaItems::LikesController < ApplicationController
  include LikeableController

  before_action :set_likeable

  private
    def set_likeable
      @likeable = MediaItem.find(params[:media_item_id])
    end
end

app/controllers/media_items_controller.rb
# frozen_string_literal: true

class MediaItemsController < ApplicationController
  include Pagy::Backend

  before_action :set_trip, only: %i[index_trip index_waypoint new_trip new_waypoint]
  before_action :set_waypoint, only: %i[index_waypoint new_waypoint]
  before_action :set_media_item, only: %i[show edit update destroy]
  authorize_resource

  def index_public
    @pagy, @media_items = pagy(MediaItem.most_popular_public, items: 24)
  end

  def index_trip
    @pagy, @media_items = pagy(@trip.media_items.order(id: :desc), items: 24)
  end

  def index_waypoint
    @pagy, @media_items = pagy(@waypoint.media_items.order(id: :desc), items: 24)
  end

  def new
    @media_item = MediaItem.new
    @media_item.waypoint = @waypoint
  end

  def new_trip
    @media_item = MediaItem.new
    render :new
  end

  def new_waypoint
    @media_item = MediaItem.new
    @media_item.waypoint = @waypoint
    render :new
  end

  def edit
    @trip = @media_item.trip
  end

  def show
  end

  def create
    @media_item = MediaItem.create(media_item_params)
    @media_item.user = current_user

    respond_to do |format|
      if @media_item.save
        Activity.create(user: current_user, subject: @media_item, action: "uploaded")
        format.html { redirect_to @media_item, notice: "Media item was successfully created." }
      else
        format.html { redirect_back fallback_location: @trip, alert: error_string("create") }
      end
    end
  end

  def update
    respond_to do |format|
      if @media_item.update(media_item_params)
        format.html { redirect_to @media_item, notice: "Media item was successfully updated." }
      else
        format.html { redirect_back fallback_location: @media_item, alert: error_string("update") }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @media_item.destroy
        format.html { redirect_to trip_media_items_path(@trip), notice: "Media item was successfully deleted." }
      else
        format.html { redirect_back fallback_location: trip_media_items_path(@trip), alert: "Media item could not be deleted." }
      end
    end
  end

  private
    def media_item_params
      params.require(:media_item).permit(%i[title description waypoint_id photo])
    end

    def set_trip
      @trip = Trip.find(params[:trip_id])
    end

    def set_waypoint
      @waypoint = Waypoint.find(params[:waypoint_id])
    end

    def set_media_item
      @media_item = MediaItem.find(params[:media_item_id] || params[:id])
      @waypoint = @media_item.waypoint
      @trip = @waypoint.trip
    end

    def error_string(action)
      "Could not #{action} media item. Errors:<br>- #{@media_item.errors.full_messages.join('<br>- ')}"
    end
end

app/helpers/media_items_helper.rb
# frozen_string_literal: true

module MediaItemsHelper
end

app/views/media_items/_form.html.erb
<%= form_with(model: media_item, local: true, id: 'media-item-form') do |f| %>
  <% if media_item.errors.any? %>
    <div class="form-error-list">
      <h2><%= pluralize(media_item.errors.count, "error") %> prohibited this media item from being saved:</h2>
      <ul>
      <% media_item.errors.full_messages.each do |e| %>
        <li><%= e %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group my-2">
    <%= f.label :waypoint %>
    <%= f.select :waypoint_id, waypoints_for_select(@trip), {}, class: 'form-select' %>
  </div>

  <div class="form-group my-2">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group my-2">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group my-2">
    <%= f.label :photo %>
    <%= f.file_field :photo, class: 'form-control' %>
  </div>
<% end %>

app/views/media_items/_media_item.html.erb
<div class="col">
  <div class="card shadow-sm">
    <%= link_to (local_assigns[:detail_view].present? ? media_item.photo : media_item) do %>
      <%= image_tag(
        (local_assigns[:detail_view].present? ? media_item.photo : media_item.photo.representation(resize_to_limit: [512, 512])),
        class: 'media-item-img', alt: media_item.title, id: dom_id(media_item)) %>
    <% end %>
    <div class="card-body">
      <p class="card-text mb-0"><i class="bi bi-geo-alt"></i> <%= "#{media_item.waypoint.name}, #{media_item.waypoint.country_name} #{media_item.waypoint.country_flag}" %></p>
      <small class="text-muted">by <%= link_to_if can?(:show, media_item.user), media_item.user, media_item.user %></small>
      <div class="media-item-bottom-bar">
        <small class="text-muted"><%= "#{time_ago_in_words(media_item.created_at)} ago" %></small>
        <div class="interaction-button-group">
          <%= render 'shared/like_button', likeable: media_item, user: current_user, clickable: can?(:create, Like) %>
          <%= render 'shared/comments_button', commentable: media_item %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/media_items/edit.html.erb
<%= render 'shared/trips_header', trip: @media_item.trip, title: 'Edit media item', navbar: false %>

<%= render 'shared/back_button', target: trip_media_items_path(@media_item.trip) %>
<%= render 'shared/confirm_button', form: 'media-item-form' %>

<%= render 'form', media_item: @media_item %>

app/views/media_items/index_public.html.erb
<h1 class="display-2 mb-4">Media gallery</h1>

<div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 g-3">
  <%= render @media_items %>
</div>

<% if @pagy.pages > 1%>
  <div class="my-5 text-center">
    <%== pagy_bootstrap_nav @pagy %>
  </div>
<% end %>

app/views/media_items/index_trip.html.erb
<%= render 'shared/trips_header', trip: @trip, title: 'Media gallery', active: 'media_items' %>

<% if can? :manage_mediaitem, @trip %>
  <%= render 'shared/add_button', target: trip_new_media_item_path(@trip), resource: 'media item' %>
<% end %>

<div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 g-3">
  <%= render @media_items %>
</div>

<% if @pagy.pages > 1%>
  <div class="my-5 text-center">
    <%== pagy_bootstrap_nav @pagy %>
  </div>
<% end %>

app/views/media_items/index_waypoint.html.erb
<%= render 'shared/trips_header', trip: @waypoint.trip, title: "Media gallery - #{@waypoint.name}", active: 'media_items' %>

<%= render 'shared/back_button', target: :back %>

<% if can? :manage_mediaitem, @trip %>
  <%= render 'shared/add_button', target: trip_waypoint_new_media_item_path(@trip, @waypoint), resource: 'media item' %>
<% end %>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
  <%= render @media_items %>
</div>

<% if @pagy.pages > 1%>
  <div class="my-5 text-center">
    <%== pagy_bootstrap_nav @pagy %>
  </div>
<% end %>

app/views/media_items/new.html.erb
<%= render 'shared/trips_header', trip: @trip, title: 'Add media item', navbar: false %>

<%= render 'shared/back_button', target: :back %>
<%= render 'shared/confirm_button', form: 'media-item-form' %>

<%= render 'form', media_item: @media_item %>

app/views/media_items/show.html.erb
<%= render 'shared/trips_header', trip: @media_item.trip, title: 'Media item', navbar: false %>

<%= render 'shared/back_button', target: trip_media_items_path(@media_item.trip) + "\##{dom_id(@media_item)}" %>
<% if can? :manage, @media_item %>
    <%= render 'shared/edit_button', target: edit_media_item_path(@media_item) %>
    <%= render 'shared/delete_button', target: media_item_path(@media_item) %>
<% end %>
<% if can? :manage, @media_item.trip %>
  <%= link_to trip_set_cover_photo_path(@media_item.trip, @media_item), method: :put, class: 'btn btn-outline-dark mb-4' do %>
    <i class="bi bi-card-image mx-1"></i>Set as cover photo
  <% end %>
<% end %>

<p class="fs-3 fw-bold"><%= @media_item.title %></p>
<p class="fs-3 fw-light"><%= @media_item.description %></p>

<%= render @media_item, detail_view: true %>

<%= render 'comments/comments', commentable: @media_item, can_comment: can?(:new_media_item, Comment) %>