config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :trips do
    get "posts", to: "posts#index_trip", as: :posts
    get "posts/new", to: "posts#new_trip", as: :new_post
    get "media_items", to: "media_items#index_trip", as: :media_items
    get "media_items/new", to: "media_items#new_trip", as: :new_media_item
    put "set_cover_photo/:media_item_id", to: "trips#set_cover_photo", as: :set_cover_photo

    post :like, to: "trips/likes#create"
    delete :like, to: "trips/likes#destroy"

    resources :comments, module: :trips
    resources :trip_users

    resources :segments do
      put "increase_sequence", to: "segments#increase_sequence", as: :increase_sequence
      put "decrease_sequence", to: "segments#decrease_sequence", as: :decrease_sequence
    end

    resources :waypoints do
      get "media_items", to: "media_items#index_waypoint", as: :media_items
      get "media_items/new", to: "media_items#new_waypoint", as: :new_media_item
      get "posts", to: "posts#index_waypoint", as: :posts
      get "posts/new", to: "posts#new_waypoint", as: :new_post
      put "increase_sequence", to: "waypoints#increase_sequence", as: :increase_sequence
      put "decrease_sequence", to: "waypoints#decrease_sequence", as: :decrease_sequence
    end
  end

  get "waypoints/search/:keyword", to: "waypoints#search", as: :waypoints_search
  get "waypoints/distance/:id_from/:id_to", to: "waypoints#distance", as: :waypoints_distance

  resources :activities, only: %i[index show] do
    resources :comments, module: :activities
    post :like, to: "activities/likes#create"
    delete :like, to: "activities/likes#destroy"
  end

  resources :posts, except: :index do
    resources :comments, module: :posts
    post :like, to: "posts/likes#create"
    delete :like, to: "posts/likes#destroy"
  end

  resources :media_items, except: :index do
    resources :comments, module: :media_items
    post :like, to: "media_items/likes#create"
    delete :like, to: "media_items/likes#destroy"
  end

  resources :users, only: :show do
    post "follow", to: "users#follow", as: :follow
    delete "unfollow", to: "users#unfollow", as: :unfollow
  end

  resources :comments, only: %i[update edit destroy] do
    post :like, to: "comments/likes#create"
    delete :like, to: "comments/likes#destroy"
  end

  get "home/index", as: :home
  get "summary/overall", as: :summary_overall
  get "summary/current_year", as: :summary_current_year
  get "summary/last_year", as: :summary_last_year

  get "media_items_public", to: "media_items#index_public", as: :media_items_public
  get "posts_public", to: "posts#index_public", as: :posts_public
  get "trips_public", to: "trips#index_public", as: :trips_public

  root "home#index"
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  include ActivitySubject
  include Likeable

  belongs_to :waypoint
  belongs_to :user
  has_one :trip, through: :waypoint
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :activities, as: :subject, dependent: :destroy

  has_rich_text :content

  attr_readonly :likes_count
  attr_readonly :comments_count

  scope :created_between, ->(date_from, date_to) { where("created_at between ? and ?", date_from, date_to) }
  scope :most_popular_public, lambda {
    joins(:waypoint)
      .joins(:trip)
      .where("trips.visibility = ?", Trip.visibilities["visibility_public"])
      .order(likes_count: :desc, comments_count: :desc)
  }

  validates :title, presence: true
  validates :content, presence: true

  def activity_string
    "a blog post"
  end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

class Posts::CommentsController < ApplicationController
  include CommentableController

  before_action :set_commentable

  private
    def set_commentable
      @commentable = Post.find(params[:post_id])
    end
end

app/controllers/posts/likes_controller.rb
# frozen_string_literal: true

class Posts::LikesController < ApplicationController
  include LikeableController

  before_action :set_likeable

  private
    def set_likeable
      @likeable = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  include Pagy::Backend

  before_action :set_trip, only: %i[index_trip index_waypoint new_trip new_waypoint]
  before_action :set_waypoint, only: %i[index_waypoint new_waypoint]
  before_action :set_post, only: %i[show edit update destroy]
  authorize_resource

  def index_public
    @pagy, @posts = pagy(Post.most_popular_public)
  end

  def index_trip
    @pagy, @posts = pagy(@trip.posts.order(id: :desc))
  end

  def index_waypoint
    @pagy, @posts = pagy(@waypoint.posts.order(id: :desc))
  end

  def new
    @post = Post.new
    @post.waypoint = @waypoint
  end

  def new_trip
    @post = Post.new
    render :new
  end

  def new_waypoint
    @post = Post.new
    @post.waypoint = @waypoint
    render :new
  end

  def edit
    @trip = @post.trip
  end

  def show
  end

  def create
    @post = Post.create(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        Activity.create(user: current_user, subject: @post, action: "wrote")
        format.html { redirect_to @post, notice: "Post was successfully created." }
      else
        format.html { redirect_back fallback_location: @trip, alert: error_string("create") }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
      else
        format.html { redirect_back fallback_location: @post, alert: error_string("update") }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @post.destroy
        format.html { redirect_to trip_posts_path(@trip), notice: "Post was successfully deleted." }
      else
        format.html { redirect_back fallback_location: trip_posts_path(@trip), alert: "Post could not be deleted." }
      end
    end
  end

  private
    def post_params
      params.require(:post).permit(%i[title content waypoint_id])
    end

    def set_trip
      @trip = Trip.find(params[:trip_id])
    end

    def set_waypoint
      @waypoint = Waypoint.find(params[:waypoint_id])
    end

    def set_post
      @post = Post.find(params[:post_id] || params[:id])
      @waypoint = @post.waypoint
      @trip = @waypoint.trip
    end

    def error_string(action)
      "Could not #{action} post. Errors:<br>- #{@post.errors.full_messages.join('<br>- ')}"
    end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def post_excerpt(post)
    "#{truncate_string(post.content.to_plain_text, 800)} [#{link_to('Read full post', post, class: 'post-detail-link')}]"
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, id: 'post-form') do |f| %>
  <% if post.errors.any? %>
    <div class="form-error-list">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% post.errors.full_messages.each do |e| %>
        <li><%= e %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group my-2">
    <%= f.label :waypoint %>
    <%= f.select :waypoint_id, waypoints_for_select(@trip), {}, class: 'form-select' %>
  </div>

  <div class="form-group my-2">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group my-2">
    <%= f.label :content %>
    <%= f.rich_text_area :content, class: 'form-control' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="col">
  <div class="card activity-card">
    <div class="card-body">
      <%= link_to post do %>
        <h5 class="card-title" id="<%= dom_id(post) %>"><%= post.title %></h5>
      <% end %>
      <small class="text-muted">
        by <%= link_to_if can?(:show, post.user), post.user, post.user %><!--
        --><%= ", #{time_ago_in_words(post.created_at)} ago" %>
      </small>
      <div class="mt-3">
        <% if local_assigns[:detail_view].present? %>
          <%= post.content %>
        <% else %>
          <%= raw post_excerpt(post) %>
        <% end %>
      </div>
    </div>
    <div class="card-footer post-bottom-bar">
      <div><i class="bi bi-geo-alt"></i> <%= "#{post.waypoint.name}, #{post.waypoint.country_name} #{post.waypoint.country_flag}" %></div>
      <div class="interaction-button-group">
        <%= render 'shared/like_button', likeable: post, user: current_user, clickable: can?(:create, Like) %>
        <%= render 'shared/comments_button', commentable: post %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/trips_header', trip: @post.trip, title: 'Edit blog post', navbar: false %>

<%= render 'shared/back_button', target: :back %>
<%= render 'shared/confirm_button', form: 'post-form' %>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1 class="display-2">Blog</h1>

<%= render 'shared/add_button', target: new_post_path, resource: 'media item' %>

<div class="row row-cols-1 g-4">
  <%= render @posts %>
</div>

<% if @pagy.pages > 1%>
  <div class="my-5 text-center">
    <%== pagy_bootstrap_nav @pagy %>
  </div>
<% end %>

app/views/posts/index_public.html.erb
<h1 class="display-2 mb-4">Blog posts</h1>

<div class="row row-cols-1 g-4 my-3">
  <%= render @posts %>
</div>

<% if @pagy.pages > 1%>
  <div class="my-5 text-center">
    <%== pagy_bootstrap_nav @pagy %>
  </div>
<% end %>

app/views/posts/index_trip.html.erb
<%= render 'shared/trips_header', trip: @trip, title: 'Blog', active: 'posts' %>

<% if can? :manage_mediaitem, @trip %>
  <%= render 'shared/add_button', target: trip_new_post_path(@trip), resource: 'blog post' %>
<% end %>

<div class="row row-cols-1 g-4">
  <%= render @posts %>
</div>

<% if @pagy.pages > 1%>
  <div class="my-5 text-center">
    <%== pagy_bootstrap_nav @pagy %>
  </div>
<% end %>

app/views/posts/index_waypoint.html.erb
<%= render 'shared/trips_header', trip: @waypoint.trip, title: "Blog - #{@waypoint.name}", active: 'posts' %>

<%= render 'shared/back_button', target: :back %>

<% if can? :manage_mediaitem, @trip %>
  <%= render 'shared/add_button', target: trip_waypoint_new_post_path(@trip, @waypoint), resource: 'blog post' %>
<% end %>

<div class="row row-cols-1 g-4">
  <%= render @posts %>
</div>

<% if @pagy.pages > 1%>
  <div class="my-5 text-center">
    <%== pagy_bootstrap_nav @pagy %>
  </div>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/trips_header', trip: @trip, title: 'New blog post', navbar: false %>

<%= render 'shared/back_button', target: trip_posts_path(@trip) %>
<%= render 'shared/confirm_button', form: 'post-form' %>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<%= render 'shared/trips_header', trip: @post.trip, title: 'Blog post', navbar: false %>

<%= render 'shared/back_button', target: trip_posts_path(@post.trip) + "\##{dom_id(@post)}" %>
<% if can? :manage, @post %>
    <%= render 'shared/edit_button', target: edit_post_path(@post) %>
    <%= render 'shared/delete_button', target: post_path(@post) %>
<% end %>

<%= render @post, detail_view: true %>

<%= render 'comments/comments', commentable: @post, can_comment: can?(:new_post, Comment) %>